# -*- coding: utf-8 -*-
"""Statistics_assign.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nq0OTIE6XDtWH_jZGbUx_chq7qMd-m7R

Q1. What are the three measures of central tendency?
"""

# The three measures of central tendency are:
# 1. Mean: The average of a dataset.
# 2. Median: The middle value of a dataset when it is ordered from least to greatest.
# 3. Mode: The most frequent value in a dataset.

""" Q2. What is the difference between the mean, median, and mode? How are they used to measure the central tendency of a dataset?"""

# The mean, median, and mode are all measures of central tendency, but they differ in how they represent the "center" of a dataset.

# Mean:
# - Represents the average value of a dataset.
# - Calculated by summing all values and dividing by the number of values.
# - Sensitive to outliers (extreme values) as they can significantly impact the mean.
# - Useful for datasets with a normal distribution or symmetrical data.

# Median:
# - Represents the middle value of a dataset when ordered from least to greatest.
# - Less sensitive to outliers compared to the mean.
# - Useful for datasets with skewed distributions or when outliers are present.

# Mode:
# - Represents the most frequent value in a dataset.
# - Useful for identifying the most common value or category in a dataset.
# - Can be used for both numerical and categorical data.
# - A dataset can have multiple modes (bimodal, trimodal, etc.) or no mode at all.

# How they are used to measure central tendency:

# - Mean: Provides a general overview of the average value in a dataset.
# - Median: Provides a measure of the "typical" value that is less affected by extreme values.
# - Mode: Provides information about the most frequent value or category in a dataset.

# The choice of which measure to use depends on the nature of the data and the specific research question. For example:

# - If the data is normally distributed and there are no outliers, the mean is a good measure of central tendency.
# - If the data is skewed or contains outliers, the median is a better measure of central tendency.
# - If the goal is to identify the most common value or category, the mode is the most appropriate measure.



"""Q3. Measure the three measures of central tendency for the given height data:
[178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5]
"""

import numpy as np
from scipy import stats

height_data = [178, 177, 176, 177, 178.2, 178, 175, 179, 180, 175, 178.9, 176.2, 177, 172.5, 178, 176.5]

# Calculate the mean
mean_height = np.mean(height_data)

# Calculate the median
median_height = np.median(height_data)

# Calculate the mode
mode_height = stats.mode(height_data)

print("Mean height:", mean_height)
print("Median height:", median_height)
print("Mode height:", mode_height)



"""Q4. Find the standard deviation for the given data:
[178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5]
"""

import numpy as np

height_data = [178, 177, 176, 177, 178.2, 178, 175, 179, 180, 175, 178.9, 176.2, 177, 172.5, 178, 176.5]

# Calculate the standard deviation
std_height = np.std(height_data)

print("Standard deviation of height:", std_height)

"""Q5. How are measures of dispersion such as range, variance, and standard deviation used to describe
the spread of a dataset? Provide an example.
"""

import numpy as np

# Measures of dispersion, such as range, variance, and standard deviation, are used to describe how spread out the data is in a dataset.
# They provide information about the variability or the degree to which data points differ from the central tendency (mean, median, or mode).

# Range:
# - The range is the simplest measure of dispersion, representing the difference between the highest and lowest values in a dataset.
# - It provides a basic understanding of the spread but can be sensitive to outliers.

# Variance:
# - Variance measures the average squared deviation of each data point from the mean.
# - It quantifies the overall variability in the dataset.
# - A higher variance indicates a greater spread of data points around the mean.

# Standard Deviation:
# - The standard deviation is the square root of the variance.
# - It provides a measure of dispersion in the same units as the original data.
# - It is widely used because it is more interpretable than variance and is less sensitive to outliers than the range.


# Example:
# Let's consider two datasets representing the test scores of two different classes:

class_A_scores = [70, 75, 80, 85, 90]
class_B_scores = [60, 70, 80, 90, 100]

# Calculate the mean for both classes
mean_A = np.mean(class_A_scores)
mean_B = np.mean(class_B_scores)

# Calculate the standard deviation for both classes
std_A = np.std(class_A_scores)
std_B = np.std(class_B_scores)

print("Mean of Class A:", mean_A)
print("Standard deviation of Class A:", std_A)
print("Mean of Class B:", mean_B)
print("Standard deviation of Class B:", std_B)

# Interpretation:
# Both classes have the same mean score (80). However, Class B has a higher standard deviation, indicating that the scores in Class B are more spread out around the mean compared to Class A.
# This means that there is more variability in the test scores of Class B, with some students scoring significantly higher and some significantly lower than the average.
# Class A has a smaller standard deviation, suggesting that the scores are more clustered around the mean, with less variability.

"""Q6. What is a Venn diagram?

"""

# A Venn diagram is a visual representation of the relationships between different sets of data.
# It uses overlapping circles or other shapes to show the common and unique elements within each set.
# Venn diagrams are widely used in various fields, including mathematics, logic, statistics, and computer science, to illustrate concepts like:
# - Set theory: Representing unions, intersections, and complements of sets.
# - Probability: Showing the likelihood of events occurring.
# - Logic: Depicting relationships between different propositions.
# - Data analysis: Comparing and contrasting different groups or categories.



"""Q7. For the two given sets A = (2,3,4,5,6,7) & B = (0,2,6,8,10). Find:
(i) A B
(ii) A ⋃ B
"""

A = {2, 3, 4, 5, 6, 7}
B = {0, 2, 6, 8, 10}

# (i) A ∩ B (Intersection of A and B)
intersection_AB = A.intersection(B)
print("(i) A ∩ B:", intersection_AB)

# (ii) A ∪ B (Union of A and B)
union_AB = A.union(B)
print("(ii) A ∪ B:", union_AB)



"""Q8. What do you understand about skewness in data?

"""

# Skewness in data refers to the lack of symmetry in the distribution of data points.
# It indicates the degree to which the data deviates from a normal distribution, which is symmetrical.
# Skewness can be either positive or negative.

# Positive Skewness:
# - The tail of the distribution is longer on the right side, and the majority of the data points are concentrated on the left side.
# - The mean is typically greater than the median.
# - Example: Income distribution, where a few individuals have very high incomes, creating a long right tail.

# Negative Skewness:
# - The tail of the distribution is longer on the left side, and the majority of the data points are concentrated on the right side.
# - The mean is typically less than the median.
# - Example: Test scores, where most students score high, but a few students score very low, creating a long left tail.

# Importance of Skewness:
# - Understanding skewness is crucial for data analysis and interpretation.
# - It helps in identifying potential outliers and understanding the nature of the data distribution.
# - It can impact the choice of statistical methods, as some methods assume a normal distribution, while others are more robust to skewness.
# - It can provide insights into the underlying processes that generate the data.

# Measuring Skewness:
# - Skewness can be measured using statistical methods, such as calculating the skewness coefficient.
# - A skewness coefficient of 0 indicates a perfectly symmetrical distribution.
# - A positive value indicates positive skewness, and a negative value indicates negative skewness.

"""Q9. If a data is right skewed then what will be the position of median with respect to mean?"""

# If a data is right skewed, the median will be less than the mean.

# Explanation:
# In a right-skewed distribution, the tail of the distribution is longer on the right side.
# This means that there are some extreme values on the right side that pull the mean towards the right.
# The median, on the other hand, is less affected by these extreme values and represents the middle value of the dataset.
# Therefore, the median will be positioned to the left of the mean in a right-skewed distribution.

"""Q10. Explain the difference between covariance and correlation. How are these measures used in
statistical analysis?
"""

# Covariance and correlation are both measures that describe the relationship between two variables.
# However, they differ in their interpretation and scale.

# Covariance:
# - Measures the extent to which two variables change together.
# - A positive covariance indicates that the variables tend to increase or decrease together.
# - A negative covariance indicates that the variables tend to move in opposite directions.
# - The magnitude of covariance is not standardized and depends on the scale of the variables.
# - It is difficult to interpret the strength of the relationship based on covariance alone.

# Correlation:
# - Measures the strength and direction of the linear relationship between two variables.
# - It is a standardized measure, ranging from -1 to +1.
# - A correlation of +1 indicates a perfect positive linear relationship.
# - A correlation of -1 indicates a perfect negative linear relationship.
# - A correlation of 0 indicates no linear relationship.
# - Correlation is easier to interpret than covariance as it provides a standardized measure of the relationship's strength.


# How are these measures used in statistical analysis?

# - Covariance and correlation are used to identify relationships between variables.
# - They are used to assess the strength and direction of the linear relationship between variables.
# - They are used in regression analysis to model the relationship between a dependent variable and one or more independent variables.
# - They are used in portfolio analysis to assess the diversification of investments.
# - They are used in risk management to assess the correlation between different risks.

# Example:

# Let's consider two variables: the price of a stock and the price of a bond.
# If the covariance between the two variables is positive, it means that the stock and bond prices tend to move in the same direction.
# If the correlation between the two variables is close to +1, it means that there is a strong positive linear relationship between the two variables.
# This information can be used to make investment decisions, such as diversifying a portfolio by investing in assets that are not highly correlated.

# In summary, covariance and correlation are both important measures for understanding the relationship between variables.
# Correlation is a more standardized and interpretable measure than covariance, making it a more commonly used measure in statistical analysis.

"""Q11. What is the formula for calculating the sample mean? Provide an example calculation for a
dataset.
"""

# Formula for calculating the sample mean:

# Sample Mean (x̄) = (Σxi) / n

# where:
# x̄ = sample mean
# Σxi = sum of all data points in the sample
# n = number of data points in the sample


# Example Calculation:

# Let's consider a dataset of exam scores:
exam_scores = [85, 90, 78, 88, 92, 80]

# Calculate the sum of all data points:
sum_scores = sum(exam_scores)

# Calculate the number of data points:
n = len(exam_scores)

# Calculate the sample mean:
sample_mean = sum_scores / n

print("The sample mean of the exam scores is:", sample_mean)



"""Q12. For a normal distribution data what is the relationship between its measure of central tendency?"""

# For a normal distribution data, the mean, median, and mode are all equal.

# Explanation:
# In a perfectly symmetrical normal distribution, the data is evenly distributed around the center.
# This means that the mean, median, and mode all coincide at the same point, representing the center of the distribution.

# Example:
# If we have a dataset that follows a normal distribution, the mean, median, and mode will all have the same value.
# This is a characteristic feature of normal distributions and can be used to identify if a dataset is approximately normally distributed.



"""Q13. How is covariance different from correlation?"""

# Covariance and correlation are both measures that describe the relationship between two variables.
# However, they differ in their interpretation and scale.

# Covariance:
# - Measures the extent to which two variables change together.
# - A positive covariance indicates that the variables tend to increase or decrease together.
# - A negative covariance indicates that the variables tend to move in opposite directions.
# - The magnitude of covariance is not standardized and depends on the scale of the variables.
# - It is difficult to interpret the strength of the relationship based on covariance alone.

# Correlation:
# - Measures the strength and direction of the linear relationship between two variables.
# - It is a standardized measure, ranging from -1 to +1.
# - A correlation of +1 indicates a perfect positive linear relationship.
# - A correlation of -1 indicates a perfect negative linear relationship.
# - A correlation of 0 indicates no linear relationship.
# - Correlation is easier to interpret than covariance as it provides a standardized measure of the relationship's strength.

# In summary:
# - Covariance measures the direction of the linear relationship between two variables.
# - Correlation measures both the direction and strength of the linear relationship between two variables.
# - Correlation is a standardized measure, while covariance is not.
# - Correlation is easier to interpret than covariance.

# Example:
# Let's consider two variables: the height and weight of individuals.
# - If the covariance between height and weight is positive, it means that taller individuals tend to weigh more.
# - If the correlation between height and weight is close to +1, it means that there is a strong positive linear relationship between height and weight.
# - This means that as height increases, weight also tends to increase in a predictable manner.



"""Q14. How do outliers affect measures of central tendency and dispersion? Provide an example."""

import numpy as np

# Example dataset with an outlier
data = [10, 12, 15, 18, 20, 100]  # 100 is an outlier

# Calculate the mean, median, and standard deviation without the outlier
mean_without_outlier = np.mean(data[:-1])
median_without_outlier = np.median(data[:-1])
std_without_outlier = np.std(data[:-1])

# Calculate the mean, median, and standard deviation with the outlier
mean_with_outlier = np.mean(data)
median_with_outlier = np.median(data)
std_with_outlier = np.std(data)

print("Without outlier:")
print("Mean:", mean_without_outlier)
print("Median:", median_without_outlier)
print("Standard Deviation:", std_without_outlier)

print("\nWith outlier:")
print("Mean:", mean_with_outlier)
print("Median:", median_with_outlier)
print("Standard Deviation:", std_with_outlier)


# Interpretation:

# The outlier significantly affects the mean, pulling it towards the higher value.
# The median is less affected by the outlier.
# The standard deviation is also significantly affected by the outlier, as it increases due to the larger spread of data caused by the outlier.

# In this example, the outlier (100) has a substantial impact on the mean and standard deviation,
# while the median remains relatively stable. This highlights the importance of considering the presence
# of outliers when interpreting measures of central tendency and dispersion.